### ISSUE TITLE
Connect Tab Zip Code Search has no validation check

### ISSUE THREAD

**Issue by jackygrahamez** [SandersForPresident/BernieAppAndroid#10]
If you go to "Connect" and then you simply tap Go, or enter an invalid zip code, the app will crash. Here is the error code

```
08-31 08:05:49.089  29747-29747/? D/FileShare-Server﹕ ServerBroadcastReceiver.onReceive - action android.intent.action.PACKAGE_ADDED // package:com.spielpark.steve.bernieapp
08-31 08:05:49.119  29318-29765/? I/AMMetaDataParserService﹕ Resource data:Loop for running activitycom.spielpark.steve.bernieapp.actMainPage
08-31 08:05:49.299  29400-29400/? D/MagazineService::MagazineBroadcastReceiver﹕ [onReceive] android.intent.action.PACKAGE_ADDED com.spielpark.steve.bernieapp
08-31 08:05:49.309  29400-29783/? D/MagazineService::MagazineService﹕ [onHandleIntent] Send broadcast to (com.spielpark.steve.bernieapp).
08-31 08:05:49.309  29431-29431/? D/KidsModeInstallerWidget﹕ PACKAGE_ADDED : package:com.spielpark.steve.bernieapp
08-31 08:05:49.579  29785-29785/? D/SPPApp﹕ [SppMessageReceiver] onReceive. ACTION_PACKAGE_ADDED. mPkgName:com.spielpark.steve.bernieapp
08-31 08:05:49.809  22900-29819/? D/PackageBroadcastService﹕ Received broadcast action=android.intent.action.PACKAGE_ADDED and uri=com.spielpark.steve.bernieapp
08-31 08:05:49.849  22900-22900/? I/ConfigFetchService﹕ onStartCommand Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.spielpark.steve.bernieapp cmp=com.google.android.gms/.config.ConfigFetchService (has extras) }
08-31 08:05:49.919  22900-22900/? D/Vision﹕ Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.spielpark.steve.bernieapp flg=0x4000010 cmp=com.google.android.gms/.vision.DependencyBroadcastReceiverProxy (has extras) }
08-31 08:05:50.099  11903-29841/? I/UpdateIcingCorporaServi﹕ Updating corpora: APPS=com.spielpark.steve.bernieapp, CONTACTS=MAYBE
08-31 08:05:50.669  22900-29869/? D/PackageBroadcastService﹕ Received broadcast action=android.intent.action.PACKAGE_REPLACED and uri=com.spielpark.steve.bernieapp
08-31 08:05:50.669  22900-22900/? D/Vision﹕ Received broadcast Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.spielpark.steve.bernieapp flg=0x4000010 cmp=com.google.android.gms/.vision.DependencyBroadcastReceiverProxy (has extras) }
08-31 08:06:06.579  29276-29276/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.spielpark.steve.bernieapp, PID: 29276
    java.lang.NumberFormatException: Invalid int: ""
            at java.lang.Integer.invalidInt(Integer.java:137)
            at java.lang.Integer.parseInt(Integer.java:358)
            at java.lang.Integer.parseInt(Integer.java:331)
            at com.spielpark.steve.bernieapp.fragments.ConnectFragment.validZip(ConnectFragment.java:222)
            at com.spielpark.steve.bernieapp.fragments.ConnectFragment.startTask(ConnectFragment.java:210)
            at com.spielpark.steve.bernieapp.fragments.ConnectFragment.access$100(ConnectFragment.java:50)
            at com.spielpark.steve.bernieapp.fragments.ConnectFragment$2.onClick(ConnectFragment.java:96)
            at android.view.View.performClick(View.java:4640)
            at android.view.View$PerformClick.run(View.java:19421)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5579)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by atticoos** [comment]
Yea I'm pretty sure it just parses an integer and checks that it's greater than 9999

**Comment by svengeance** [comment]
Fixed. Also fixed for crappy use-cases where somebody tried to enter in letters. Broke when I added support to cancel the map-loading task.
